language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: cloudshack
  api_key:
    secure: YOrCG3MwAxUtwLXQZrFbXpLx6HksmXoJ8mPLCSaq3tpnllmZi+RaJjbBoJZlV3vAUzT9D8kKJ1zvVMSBRS1yb4GP8R+RQzrtbAtz3g173tpGbUXVTVzD09uoBeLhbc//f5aizgxVBjYEWeX821qWEwMw0oD3merLOQHA6DNTa+FkuY+CV+l+pmvyTdXxGgVStLGk+KZQIWZyFZLrk7qQSMmH3nd97kWHOI/bCD2vGf9cYf0H91l0SdBB4/Um+LFVpiSPsZCZXxaQOgFSw0qqbml30kj08ikJBlK43ReBg0JWbvO4o+HWK1I9c05bd7kwpAqNTwBdWndttdM8bJmqI6dGndBKjkwTOyRZUxcRE0OIKnzNgPA0S3C+aBWksNA7z8La+2nt7VZQFF3n3KsuRlOqhv+rO96cv4ZBoto/+hxFb8TFzeYXfC6jOI4e/k/1jtpCmttTmfkXJjK07UB7Hk/crIDhb15++8nOIym1moAsKD7+IEs8uhroeoHQfrjZ6JILTd1MT+NrKOtBW464tmFdjI7NrLgxogimjsqZ9vbl4nTITp2DjGgjmPFnt94qhtOEgJ+C63VBpGvPPtH8uUvXdcYjXWAnr4Yu7wAQ0oqQ1nOzQcblAnp2qL5LPofZXL8llLjyPGyNKlyaH76CefvtufQJxLvKDv5Wta1yLxg=
